# Generated by Django 4.1.1 on 2022-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=500)),
                ('purebred', models.BooleanField(default=False)),
                ('crossbreed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['breed'],
            },
        ),
    ]
