# Generated by Django 4.1.1 on 2022-10-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='gender',
            new_name='enjoy',
        ),
    ]
