# Generated by Django 4.1.1 on 2022-10-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_toy_doggo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='enjoy',
        ),
        migrations.AddField(
            model_name='toy',
            name='img',
            field=models.CharField(max_length=250, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='dog',
            name='img',
            field=models.CharField(max_length=250, null='True'),
        ),
    ]
