# Generated by Django 4.1.1 on 2022-10-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_playlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist',
            new_name='Favorite',
        ),
    ]
