# Generated by Django 4.1.1 on 2022-10-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_dog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='top',
            new_name='toys',
        ),
    ]
