# Generated by Django 4.1.1 on 2022-10-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='breed',
            new_name='name',
        ),
    ]
