# Generated by Django 4.1.1 on 2022-10-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_gender_toy_enjoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='doggo',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='main_app.dog'),
            preserve_default='True',
        ),
    ]
