# Generated by Django 4.1.1 on 2022-10-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_playlist_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='top',
            new_name='doggo',
        ),
        migrations.AddField(
            model_name='favorite',
            name='img',
            field=models.CharField(max_length=250, null='True'),
            preserve_default='True',
        ),
    ]
