# Generated by Django 4.1.1 on 2022-10-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_doggo_favorite_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='img',
        ),
    ]
